### ISSUE TITLE
Ethercalc Crashes Unexpectedly

### ISSUE THREAD

**Issue by nerdymark** [audreyt/ethercalc#251] opened 2015-10-15 15:11 UTC
Hello all,
I have this application deployed on an Ubuntu server. I'm running the latest Node.js and Ethercalc.

My end-user has reported that when she attempts to hide a row, the crash happens. I haven't confirmed this personally. Any insight on the issue would be appreciated.

evalmachine.<anonymous>:9740
         headercell = editor.fullgrid.childNodes[1].childNodes[1].childNodes[1+colindex+ecell.col-first];
                                     ^
TypeError: Cannot read property 'childNodes' of null
    at Object.SocialCalc.SetECellHeaders (evalmachine.<anonymous>:9740:38)
    at SocialCalc.TableEditor.SetECellHeaders (evalmachine.<anonymous>:7498:83)
    at Object.SocialCalc.MoveECell (evalmachine.<anonymous>:9602:14)
    at SocialCalc.TableEditor.MoveECell (evalmachine.<anonymous>:7495:83)
    at SocialCalc.EditorSheetStatusCallback [as statuscallback] (evalmachine.<anonymous>:7955:20)
    at Object.SocialCalc.SheetCommandsTimerRoutine (evalmachine.<anonymous>:2550:20)
    at evalmachine.<anonymous>:2522:18
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by ldidry** [comment] 2016-03-07 16:49
I got the same issue: I encapsulated the block in `if (editor.fullgrid !== null) {` in `socialcalctableeditor.js` (there is an other block trying to access `editor.fullgrid.childNodes[1]` a few lines below, I needed to encapsulated it too) and then restarted ethercalc.

**Comment by audreyt** [comment] 2016-03-07 16:59
Luc I just made you collaborator to this repo; please feel free to commit to `master` and close this ticket once you do. :rainbow:

**Comment by ldidry** [comment] 2016-03-07 17:01
Awesome :smile:

**Comment by ldidry** [comment] 2016-03-07 17:55
Hum, running `make` to check if I didn't break anything changed some other files:

- SocialCalcModule.js (logical)
- static/ethercalc.js (logical)

But it modified too:
- db.js
- emailer.js
- main.js
- player-broadcast.js
- player-graph.js
- player.js

These modifications are caused by the use of livescript 1.4.0 (they were generated by livescript 1.2.0).

Do I need to include these modified files in the commit?

**Comment by audreyt** [comment] 2016-03-07 20:38
Sure, please do.

Luc Didry <notifications@github.com> 於 2016年3月7日週一 18:55 寫道：

> Hum, running make to check if I didn't break anything changed some other
> files:
>
>    - SocialCalcModule.js (logical)
>    - static/ethercalc.js (logical)
>
> But it modified too:
>
>    - db.js
>    - emailer.js
>    - main.js
>    - player-broadcast.js
>    - player-graph.js
>    - player.js
>
> These modifications are caused by the use of livescript 1.4.0 (they were
> generated by livescript 1.2.0).
>
> Do I need to include these modified files in the commit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audreyt/ethercalc/issues/251#issuecomment-193370315>.
>
-- 

Cheers,
Audrey

**Closed** 2016-03-08 13:42 UTC
