### ISSUE TITLE
Drop-down selector empty

### ISSUE THREAD

**Issue by Trollken** [audreyt/ethercalc#685] opened 2019-09-24 14:48 UTC
Hi, and thks for this beautiful piece of software,

I've got a little problem with the select function which often is unusable.

- I have a spreadsheet with some data
- I have a second spreadsheet with a SELECT function referencing the first spreadsheet data (same SELECT in each B2:B8 cells).

When I create my sheet, everything is fine. But then I go to the form view (/app) and every dropdown menus are empty.

![2019-09-24_16-37](https://user-images.githubusercontent.com/49722498/65522381-f5db1500-deea-11e9-9d6e-03b6dc1a1b15.png)
![2019-09-24_16-38](https://user-images.githubusercontent.com/49722498/65522388-f8d60580-deea-11e9-870c-7cd4c6985fea.png)

If I go back to the edit view, the dropdown menus are also empty, and I need to make a change in the formula to make it appear again.

I don't understand what's happening ??

Regards,

EDIT : I just noticed, when going to the "previous revision" page, I see this error in the cells that don't work : "error:Widget HTML missing".
Probably linked ??

**Comment by eddyparkinson** [comment] 2019-09-26 01:16
Error in the sheet?
Can you try it with a single select in the sheet. i.e. minimal sheet so you are sure there are no errors in the formulas.  .... So errors in the sheet can cause this, as an error stops the recalc form working as you want.  These can be hard to find when you get a lot of formulas in the sheet.  I need a better way to show the error message in app mode.

Or ... can you create the error and paste the audit tab here


This works:

https://ethercalc.org/testselect/app
https://ethercalc.org/testselect

**Comment by Trollken** [comment] 2019-09-26 09:44
Well, in fact, even the simpliest select doesn't work.

For example, in the cell F2, I put the following : 
=SELECT("J01","J01,J02,J03,J04,J05,J06,J07,J08,J09,J10,J11,J12,J13,J14")

When I load the app view, the drop-down menus don't work. If in another web browser tab I change something in the sheet, the app tab is refreshing itself and it works.
The change must be something more than simply filling up some texte in a cell. I have to paste something, or to use the "fill" function (works even if I do it on empty cells).

Looks like using more "complex" functions of the spreadsheet changes something...

https://ethercalc.org/assgabad1/app
https://ethercalc.org/assgabad1

**Comment by eddyparkinson** [comment] 2019-09-27 01:41
Case sensitive sheet names
---

Sheet names are case sensitive.

=SELECT("Omega Lejeune",ASSGASOURCE!A2:B55)
=SELECT("Omega Lejeune",assgasource!A2:B55)

These are 2 not the same.

Note this is not always consistent, there are cases where case is ignored. Not sure of the rule, but suspect at load time the sheet names are case sensitive. 

Closing this, let me know how you get on.

**Comment by eddyparkinson** [comment] 2019-09-27 02:50
re-opened - I don't think that is the cause. 

I think you can't use other sheets with gui formula - I think calculation order was hard to handle.

It is why it works after everything has loaded and then you trigger a re-calc of the sheet.

**Comment by Trollken** [comment] 2019-09-27 05:57
Looks like you found the problem, with all the data in the same sheet it works ! :)

I used the splash formula to hide the data. May I ask what is the goal of the panel formula ? I saw many examples of its use but I still don't get how it works

**Comment by eddyparkinson** [comment] 2019-09-27 06:41
panel uses hide row/col to hide things. so you need to have things above each other for it to work.


So this is hiding rows - and when you press the buttons, it changes which rows are hidden.
http://sheet.cellmaster.com.au/example_panel/appeditor

**Closed** 2019-09-27 06:41 UTC
