### ISSUE TITLE
wrong encoding on PUT text/csv

### ISSUE THREAD

**Issue by a-tsioh** [audreyt/ethercalc#682] opened 2019-09-15 15:49 UTC
With the current version, encoding is messed up when PUTing a csv file with non-ascii letters to ethercalc.
It used not to be the case. I tried on my own instance and ethercalc.org , both have a wrong behaviour (framacalc seems not affected).

My investigation led to the X.read function in the `xlsx` dependency of the `j` dependency. (It may have changed recently, I didn't checked).

A work around can be to pre-encode the buffer in utf8 and specify an option object `{'type': 'string'}` to the call of `J.read` in `request-to-save`.

It worked for me but I'm not quite sure about possible side-effect (I am assuming utf-8 input).

**Comment by eddyparkinson** [comment] 2019-09-16 06:16
I tried:

日,sun
一,one
大,big


on https://ethercalc.org
both UTF8 & Unicode failed.

Your comment suggest that, maybe the new version of j is the cause: https://github.com/audreyt/ethercalc/commit/c028abbc9ff1570f9649cb1fa456403e28922085

**Comment by joebordes** [comment] 2020-01-04 21:33
is there any solution to this?  This regression practically makes the project useless. Where should we start migrating to?

**Comment by eddyparkinson** [comment] 2020-01-14 01:34
Try with http://sheet.cellmaster.com.au/

If it works, then these may work: 
https://github.com/eddyparkinson/js-harb
https://github.com/eddyparkinson/js-xlsx
https://github.com/eddyparkinson/j

**Comment by mocodertz** [comment] 2020-02-03 13:59
Yes, it works with your link. Is your install previous to the J update or a newer branch that has been updated?  What should I do?

**Comment by eddyparkinson** [comment] 2020-02-03 23:26
Fix
---

Please try the latest NPM release - the changes should fix the issue, as they force it to use an older version of js-xlsx.

**Comment by eddyparkinson** [comment] 2020-03-05 03:26
Should now be fixed. Let us know if not. Closing issue.

**Closed by eddyparkinson** 2020-03-05 03:26 UTC
Labels: bug
