### ISSUE TITLE
Crashes on opening certain table

### ISSUE THREAD

**Issue by t2d** [audreyt/ethercalc#325] opened 2016-04-04 18:10 UTC
this does the syslog say while crashing
```
ethercalc[2626]: evalmachine.<anonymous>:9788
ethercalc[2625]: headercell = editor.fullgrid.childNodes[1].childNodes[2+rowindex+ecel
ethercalc[2625]: ^
ethercalc[2625]: TypeError: Cannot read property 'childNodes' of null
ethercalc[2625]: at Object.SocialCalc.SetECellHeaders (evalmachine.<anonymous>:9788:38)
ethercalc[2625]: at SocialCalc.TableEditor.SetECellHeaders (evalmachine.<anonymous>:7498:83)
ethercalc[2625]: at Object.SocialCalc.MoveECell (evalmachine.<anonymous>:9665:14)
ethercalc[2625]: at SocialCalc.TableEditor.MoveECell (evalmachine.<anonymous>:7495:83)
ethercalc[2625]: at SocialCalc.EditorSheetStatusCallback [as statuscallback] (evalmachine.<anonymous>:7956:20)
ethercalc[2625]: at Object.SocialCalc.SheetCommandsTimerRoutine (evalmachine.<anonymous>:2550:20)
ethercalc[2625]: at evalmachine.<anonymous>:2522:18
ethercalc[2625]: at process._tickCallback (node.js:419:13)
systemd[1]: ethercalc.service: main process exited, code=exited, status=8/n/a
```

**Comment by eddyparkinson** [comment] 2016-04-29 23:25
It looks like the header cell does not exist. Have you got a URL for the sheet?

**Comment by t2d** [comment] 2016-05-02 07:03
Dear @eddyparkinson 

I'm really sorry, the original url is not available anymore. At the time, I was able to export the csv via API -> [test.csv.txt](https://github.com/audreyt/ethercalc/files/244618/test.csv.txt)
During loading, I could see, that the style of the table was heavily edited. Probably something of this caused the trouble. Than the service crashed.

**Comment by ldidry** [comment] 2016-05-02 07:12
Are you using the last version of ethercalc? This shouldn't happen since the commit 495693fcec637d0c7ec521320b51677d85c8dd3a (unless it's the `childNodes[1]` or the `childNodes[2+rowindex+ecell.row-first]` which is null and not `editor.fullgrid`).

Seems like a duplicate of #251 to me.

**Comment by eddyparkinson** [comment] 2016-05-02 08:49
@ldidry  **crashing problem** 

**1) hide col A - the server crashes**
if you hide col A it crashes - as I just put a fix in my code - I will add to master in a few days. 
  i.e. open a bank sheet, hide col A - the server crashes

fix:
-      editor.cellhandles.ShowCellHandles(false);
+      if(editor.cellhandles) editor.cellhandles.ShowCellHandles(false); // only if row/col visible 

**2) Unusable sheet problem** 
When a crash happens, the sheet typically become unusable.

 Because of the unusable sheet problem, I have started adding a solution. When' a crash
 happens I catch the error and issue an "undo" command.   It is a bit experimental. but looks
 to work. I also issue an alert of the error to the user and log it. With luck most sheets should be still usable after a crash.

 In the last week I have lost 2 sheets because of 2 bugs. While I can fix things, a normal user is unable to fix bugs and recover the sheet.


**3)  > Seems like a duplicate of #251 to me.**
Yes  I agree, would be good to know what version @t2d  is using

**Comment by t2d** [comment] 2016-05-03 07:15
`package.json` says
```
"version": "0.20151108.1",
```

**Comment by ldidry** [comment] 2016-05-03 07:34
You should update it ([last version is 0.20160501.1](https://www.npmjs.com/package/ethercalc)) and check if the problem is still present.

**Comment by t2d** [comment] 2016-05-03 07:41
Since I did not create the original sheet, I do not know how to reproduce the error. If you believe it is a duplicate, feel free to close the issue.

**Closed** 2016-05-22 07:11 UTC
